version: "3"

services:
  wordpress:
    image: registry.gitlab.com/betterthanyou/americagambles.com/wordpress/master:latest
    volumes:
      - "wordpress_uploads:/var/www/html/wp-content/uploads"
      - "wordpress_cache:/var/www/html/wp-content/cache"
      - "wordpress_webp:/var/www/html/wp-content/webp-express"
    environment:
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_HOST: "${RDS_HOST}:3306"
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_DB_PREFIX}
      WORDPRESS_ENV: ${WORDPRESS_ENV}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_CACHE', true);
        define('DISABLE_WP_CRON', true);
        define( 'WP_DEBUG', true );
        define( 'WP_DEBUG_DISPLAY', false );
        define( 'WP_DEBUG_LOG', true );
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  proxy:
    image: registry.gitlab.com/betterthanyou/americagambles.com/nginx/master:latest
    depends_on:
      - varnish
    volumes:
      - "geolite2-dbs:/etc/nginx/geolite2"
    networks:
      - backend
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik
        - traefik.http.routers.americagambles-wp.rule=Host(`americagambles.com`) || Host(`www.americagambles.com`)
        - traefik.http.routers.americagambles-wp.entrypoints=websecure
        - traefik.http.routers.americagambles-wp.tls.certresolver=le1
        - traefik.http.routers.americagambles-wp.service=americagambles-wp-service
        - traefik.http.services.americagambles-wp-service.loadbalancer.server.port=80
        - traefik.http.routers.americagambles-wp-http.rule=Host(`americagambles.com`) || Host(`www.americagambles.com`)
        - traefik.http.routers.americagambles-wp-http.entrypoints=web
        - traefik.http.routers.americagambles-wp-http.middlewares=americagambles-wp-mw2
        - traefik.http.middlewares.americagambles-wp-mw2.redirectscheme.scheme=https
        - traefik.http.middlewares.americagambles-wp-mw2.redirectscheme.permanent=true
  varnish:
    depends_on:
      - wordpress
    image: registry.gitlab.com/betterthanyou/americagambles.com/varnish/master:latest
    networks:
      - backend


networks:
  traefik:
    external: true
  backend:

volumes:
  wordpress_uploads:
    driver: local
  wordpress_cache:
    driver: local
  wordpress_webp:
    driver: local
  geolite2-dbs:
    external: true