<?php
if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group(array(
                                  'key'                   => 'group_6027f2150e7aa',
                                  'title'                 => 'Project Settings',
                                  'fields'                => array(
                                      array(
                                          'key'               => 'field_602817a99e67e',
                                          'label'             => 'thumbnail',
                                          'name'              => 'thumbnail',
                                          'type'              => 'image',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'return_format'     => 'array',
                                          'preview_size'      => 'medium',
                                          'library'           => 'all',
                                          'min_width'         => '',
                                          'min_height'        => '',
                                          'min_size'          => '',
                                          'max_width'         => '',
                                          'max_height'        => '',
                                          'max_size'          => '',
                                          'mime_types'        => '',
                                      ),
                                      array(
                                          'key'               => 'field_6027f2296ebcb',
                                          'label'             => 'Subline long',
                                          'name'              => 'subline_long',
                                          'type'              => 'text',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '50',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'default_value'     => '',
                                          'placeholder'       => '',
                                          'prepend'           => '',
                                          'append'            => '',
                                          'maxlength'         => '',
                                      ),
                                      array(
                                          'key'               => 'field_6027f2456ebcc',
                                          'label'             => 'Subline short',
                                          'name'              => 'subline_short',
                                          'type'              => 'text',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '50',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'default_value'     => '',
                                          'placeholder'       => '',
                                          'prepend'           => '',
                                          'append'            => '',
                                          'maxlength'         => '',
                                      ),
                                      array(
                                          'key'               => 'field_6027f21e6ebca',
                                          'label'             => 'Settings',
                                          'name'              => 'settings',
                                          'type'              => 'group',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'layout'            => 'block',
                                          'sub_fields'        => array(
                                              array(
                                                  'key'               => 'field_6027f2786ebce',
                                                  'label'             => 'Customer Name',
                                                  'name'              => 'customer_name',
                                                  'type'              => 'text',
                                                  'instructions'      => '',
                                                  'required'          => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper'           => array(
                                                      'width' => '50',
                                                      'class' => '',
                                                      'id'    => '',
                                                  ),
                                                  'default_value'     => '',
                                                  'placeholder'       => '',
                                                  'prepend'           => '',
                                                  'append'            => '',
                                                  'maxlength'         => '',
                                              ),
                                              array(
                                                  'key'               => 'field_6027f2836ebcf',
                                                  'label'             => 'URL',
                                                  'name'              => 'url',
                                                  'type'              => 'text',
                                                  'instructions'      => '',
                                                  'required'          => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper'           => array(
                                                      'width' => '50',
                                                      'class' => '',
                                                      'id'    => '',
                                                  ),
                                                  'default_value'     => '',
                                                  'placeholder'       => '',
                                                  'prepend'           => '',
                                                  'append'            => '',
                                                  'maxlength'         => '',
                                              ),
                                              array(
                                                  'key'               => 'field_6027f28d6ebd0',
                                                  'label'             => 'Year',
                                                  'name'              => 'year',
                                                  'type'              => 'text',
                                                  'instructions'      => '',
                                                  'required'          => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper'           => array(
                                                      'width' => '50',
                                                      'class' => '',
                                                      'id'    => '',
                                                  ),
                                                  'default_value'     => '',
                                                  'placeholder'       => '',
                                                  'prepend'           => '',
                                                  'append'            => '',
                                                  'maxlength'         => '',
                                              ),
                                              array(
                                                  'key'               => 'field_6027f2a36ebd1',
                                                  'label'             => 'Service',
                                                  'name'              => 'service',
                                                  'type'              => 'text',
                                                  'instructions'      => '',
                                                  'required'          => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper'           => array(
                                                      'width' => '50',
                                                      'class' => '',
                                                      'id'    => '',
                                                  ),
                                                  'default_value'     => '',
                                                  'placeholder'       => '',
                                                  'prepend'           => '',
                                                  'append'            => '',
                                                  'maxlength'         => '',
                                              ),
                                              array(
                                                  'key'               => 'field_6027f2b36ebd2',
                                                  'label'             => 'Description',
                                                  'name'              => 'description',
                                                  'type'              => 'wysiwyg',
                                                  'instructions'      => '',
                                                  'required'          => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper'           => array(
                                                      'width' => '',
                                                      'class' => '',
                                                      'id'    => '',
                                                  ),
                                                  'default_value'     => '',
                                                  'tabs'              => 'all',
                                                  'toolbar'           => 'full',
                                                  'media_upload'      => 1,
                                                  'delay'             => 0,
                                              ),
                                              array(
                                                  'key'               => 'field_6028170ec6872',
                                                  'label'             => 'Gallery',
                                                  'name'              => 'gallery',
                                                  'type'              => 'gallery',
                                                  'instructions'      => '',
                                                  'required'          => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper'           => array(
                                                      'width' => '',
                                                      'class' => '',
                                                      'id'    => '',
                                                  ),
                                                  'return_format'     => 'array',
                                                  'preview_size'      => 'medium',
                                                  'insert'            => 'append',
                                                  'library'           => 'all',
                                                  'min'               => '',
                                                  'max'               => '',
                                                  'min_width'         => '',
                                                  'min_height'        => '',
                                                  'min_size'          => '',
                                                  'max_width'         => '',
                                                  'max_height'        => '',
                                                  'max_size'          => '',
                                                  'mime_types'        => '',
                                              ),
                                          ),
                                      ),
                                  ),
                                  'location'              => array(
                                      array(
                                          array(
                                              'param'    => 'post_type',
                                              'operator' => '==',
                                              'value'    => 'projects',
                                          ),
                                      ),
                                  ),
                                  'menu_order'            => 0,
                                  'position'              => 'normal',
                                  'style'                 => 'default',
                                  'label_placement'       => 'top',
                                  'instruction_placement' => 'label',
                                  'hide_on_screen'        => '',
                                  'active'                => true,
                                  'description'           => '',
                              ));

endif;