FROM nginx:1.17.6
ENV LIBMAXMIND_VERSION=1.4.2

RUN set -ex; \
    \
    apt update && \
    apt-get install -y build-essential wget openssl && \
    wget -qO - https://github.com/maxmind/libmaxminddb/releases/download/${LIBMAXMIND_VERSION}/libmaxminddb-${LIBMAXMIND_VERSION}.tar.gz | tar zxfv - && \
    cd libmaxminddb-${LIBMAXMIND_VERSION}/ && \
    ./configure && \
    make && \
    make install && \
    ldconfig && \
    cd ../ && rm -r libmaxminddb-${LIBMAXMIND_VERSION}/ && \
    apt-get remove --purge --auto-remove -y build-essential wget && rm -rf /var/lib/apt/lists/*

RUN set -ex; \
    \
    apt update && apt install nano && rm -rf /var/lib/apt/lists/*
COPY ngx_http_geoip2_module.so /usr/lib/nginx/modules/ngx_http_geoip2_module.so
COPY nginx.conf /etc/nginx/nginx.conf
